// Run against frontend_smoke_server; never calls live research/model providers.
const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');

(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'chrome' });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [];
    let researchRequests = 0;
    page.on('pageerror', error => errors.push(error.message));
    page.on('request', request => { if (request.url().endsWith('/api/v1/runs/stream')) researchRequests++; });
    await page.goto('http://127.0.0.1:8768/?demo=1');
    const alpha = page.locator('.map-node.product').filter({ has: page.locator('text.node-label', { hasText: 'alpha' }) });
    await alpha.waitFor();
    await alpha.click();
    await page.locator('#detail-facts').getByText('Key capabilities', { exact: true }).waitFor();
    const detail = await page.locator('#detail-facts').innerText();
    assert.match(detail, /feedback/);
    assert.match(detail, /subscription/);
    assert.match(detail, /Semantic positioning/);
    assert.match(detail, /Pricing evidence limited/);
    assert.doesNotMatch(detail, /Missing structured field|analysis path was unavailable|business_model|target_users/);
    const source = page.locator('#detail-sources a').first();
    assert.equal(await source.getAttribute('href'), 'https://alpha.example/');
    assert.match(await source.getAttribute('title'), /interview coaching/);
    await page.locator('#compare-toggle').click();
    await page.locator('#close-detail').click();
    const beta = page.locator('.map-node.product').filter({ has: page.locator('text.node-label', { hasText: 'beta' }) });
    await beta.waitFor();
    await beta.focus();
    await page.keyboard.press('Enter');
    await page.locator('#compare-toggle').click();
    const matrix = await page.locator('#compare-table-wrap').innerText();
    assert.match(matrix, /YOUR IDEA/);
    assert.match(matrix, /job seekers/i);
    assert.match(matrix, /Practice, receive feedback, and retry/);
    assert.match(matrix, /subscription/);
    assert.doesNotMatch(matrix, /Unknown/);
    assert.match(await page.locator('#compare-synthesis').innerText(), /Focus Ring|does not establish/);
    await page.waitForFunction(() => document.querySelectorAll('.map-node.product').length === 3);
    assert.equal(await page.locator('.map-node.selected .node-label').textContent(), 'beta');
    assert.equal(await page.locator('.map-node.focus').count() > 0, true);
    assert.ok(await page.locator('#focus-ring').getAttribute('d'));
    assert.equal(await page.locator('#cluster-layer circle.cluster-region').count(), 0);
    const uncategorized = page.locator('.cluster-territory.uncategorized');
    if (await uncategorized.count()) assert.equal(await uncategorized.first().isVisible(), false);
    assert.equal(await page.locator('#replay-focus').isVisible(), true);
    await page.locator('#close-detail').click();
    await page.locator('#clear-compare').click();
    const positions = await page.locator('.map-node').evaluateAll(nodes => nodes.map(node => node.getAttribute('transform')));
    await page.locator('#replay-focus').click();
    await page.waitForTimeout(450);
    assert.equal(await page.locator('#market-map').evaluate(node => node.classList.contains('focus-spotlight')), true);
    assert.equal(await page.locator('#focus-layer').evaluate(node => node.classList.contains('drawing')), true);
    assert.deepEqual(await page.locator('.map-node').evaluateAll(nodes => nodes.map(node => node.getAttribute('transform'))), positions);
    await page.waitForTimeout(400);
    assert.equal(await page.locator('#focus-layer').evaluate(node => node.classList.contains('field-visible')), true);
    await page.waitForTimeout(400);
    assert.equal(await page.locator('#focus-layer').evaluate(node => node.classList.contains('label-visible')), true);
    await page.waitForTimeout(400);
    assert.equal(await page.locator('#market-map').evaluate(node => node.classList.contains('focus-spotlight')), false);
    assert.doesNotMatch(await page.locator('#run-status').innerText(), /complete/i);
    assert.equal(researchRequests, 1, 'Compare must not start research');
    await page.locator('#presentation-mode').click();
    assert.match(await page.locator('#presentation-footer').innerText(), /3 PRODUCTS MAPPED · 3 VALIDATED · 3 UNIQUE SOURCES/i);
    assert.equal(await page.locator('body').evaluate(node => node.classList.contains('presentation-mode')), true);
    assert.equal(await page.locator('.insight-strip').isVisible(), false);
    assert.equal(await page.locator('#presentation-export-png').isVisible(), true);
    assert.equal(await page.locator('#presentation-export-svg').isVisible(), true);
    await page.locator('#exit-presentation').click();
    const downloadPromise = page.waitForEvent('download');
    await page.locator('#export-svg').click();
    const download = await downloadPromise;
    const stream = await download.createReadStream();
    let svg = ''; for await (const chunk of stream) svg += chunk;
    assert.match(svg, /alpha/); assert.match(svg, /beta/); assert.match(svg, /3 products mapped · 3 validated · 3 unique sources/i);
    assert.doesNotMatch(svg, /CLOSEST RIVALS|YOUR DIFFERENTIATION|OPPORTUNITY AROUND YOU/);
    await page.waitForFunction(() => document.querySelector('#run-status').textContent.includes('Research complete'));
    await page.locator('#new-map').click();
    assert.equal(await page.locator('.map-node.product').count(), 0);
    assert.equal(await page.locator('#framing-question').innerText(), 'What are you building?');
    await page.locator('#demo-mode').click();
    await page.locator('.map-node.product').first().waitFor();
    assert.equal(researchRequests, 2, 'Run demo must start a fresh research stream');
    assert.deepEqual(errors, []);
    console.log('PASS: progressive SSE → detail/Compare → Presentation/export → New map reset → Run demo restart; no page errors.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
